#! /bin/sh

name=gettext
version=0.23.1
revision=1
tarball_url="https://ftpmirror.gnu.org/gnu/gettext/gettext-${version}.tar.xz"
tarball_blake2b="08d10340f3d855a87a96594c6f2dcf72925394f02e86235090f8d272e0a27ce32e57a0fbaed61aaf61d7328ff30be076dccaecaa13832d8db3ec0a51786780b9"
hostdeps="automake autoconf libtool pkg-config"

prepare() {
    ( cd gettext-runtime/libasprintf && autoreconf -fvi )
    ( cd gettext-runtime/intl && autoreconf -fvi )
    ( cd gettext-runtime && autoreconf -fvi )
    ( cd gettext-tools && autoreconf -fvi )
    ( cd libtextstyle && autoreconf -fvi )
    autoreconf -fvi

    for f in $(grep -rl 'GNU config.sub ($timestamp)'); do
        mv "$f" "$f".reference
        cp -v ${base_dir}/support/config.sub "$f"
        touch -r "$f".reference "$f"
        rm -f "$f".reference
    done
    for f in $(grep -rl 'GNU config.guess ($timestamp)'); do
        mv "$f" "$f".reference
        cp -v ${base_dir}/support/config.guess "$f"
        touch -r "$f".reference "$f"
        rm -f "$f".reference
    done
}
