#! /bin/sh

name=base-files
version=0.0
revision=4
source_dir="extras/base-files"
skip_pkg_check=yes

package() {
    mkdir -pv "${dest_dir}/dev"
    mkdir -pv "${dest_dir}/etc"
    mkdir -pv "${dest_dir}/home/svr4"
    mkdir -pv "${dest_dir}/run"
    mkdir -pv "${dest_dir}/root"
    mkdir -pv "${dest_dir}/tmp"
    mkdir -pv "${dest_dir}/tmp/.X11-unix"
    mkdir -pv "${dest_dir}/usr"
    mkdir -pv "${dest_dir}/usr/bin"
    mkdir -pv "${dest_dir}/usr/lib"
    mkdir -pv "${dest_dir}/usr/sbin"
    mkdir -pv "${dest_dir}/usr/share"
    mkdir -pv "${dest_dir}/var"
    mkdir -pv "${dest_dir}/var/lib/xkb"
    mkdir -pv "${dest_dir}/var/log"
    mkdir -pv "${dest_dir}/stand"

    chmod 1777 "${dest_dir}/tmp" "${dest_dir}/tmp/.X11-unix"

    ln -svf usr/bin "${dest_dir}/bin"
    ln -svf usr/lib "${dest_dir}/lib"
    ln -svf usr/sbin "${dest_dir}/sbin"
    ln -svf ../run "${dest_dir}/var/run"

    cp -rpv ${source_dir}/. "${dest_dir}"/
    chmod +x "${dest_dir}/root/.xinitrc"

    find "${dest_dir}" -type d -empty -exec touch {}/.keep \;
}
