#! /bin/sh

name=libice
version=1.1.2
revision=1
git_url="https://gitlab.freedesktop.org/xorg/lib/libice.git"
commit="adf389fc19aedbf1be077b05365d164cd6f463d8"
imagedeps="build-essential"
hostrundeps="automake autoconf libtool xorg-macros pkg-config xtrans"
hostdeps="gcc pkg-config xtrans"
deps="core-libs xorg-util-macros xorg-proto libX11 libxtrans"

prepare() {
    NOCONFIGURE=1 ./autogen.sh
}

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
