#! /bin/sh

name=libsm
version=1.1.2
revision=1
git_url="https://gitlab.freedesktop.org/xorg/lib/libsm.git"
commit="5f6da959a34bcefc425b6e37462553acf44369a3"
imagedeps="build-essential"
hostrundeps="automake autoconf libtool xorg-macros pkg-config xtrans"
hostdeps="gcc pkg-config xtrans"
deps="core-libs xorg-util-macros xorg-proto libice libX11 libxtrans"

prepare() {
    NOCONFIGURE=1 ./autogen.sh
}

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
