#! /bin/sh

name=libXmu
version=1.3.1
revision=1
git_url="https://gitlab.freedesktop.org/xorg/lib/libXmu.git"
commit="cdf280f6611932f79ab872832974e8043b1cad6d"
imagedeps="build-essential"
hostrundeps="automake autoconf libtool xorg-macros pkg-config xtrans"
hostdeps="gcc pkg-config xtrans"
deps="core-libs xorg-proto libX11 libXext libXt libxtrans xorg-util-macros"

prepare() {
    NOCONFIGURE=1 ./autogen.sh
}

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
