#! /bin/sh

name=libxtrans
from_source=xtrans
revision=1
imagedeps="build-essential"
hostrundeps="automake autoconf libtool xorg-macros pkg-config xtrans"
hostdeps="gcc pkg-config xtrans"
deps="xorg-proto libxcb"

configure() {
    autotools_configure \
        --with-keysymdefdir=${sysroot}${prefix}/include/X11 \
        --disable-ipv6 \
        --disable-malloc0returnsnull
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

        strip_command=strip \
    post_package_strip
}
