#! /bin/sh

name=libX11
version=1.8.13
revision=1
git_url="https://gitlab.freedesktop.org/xorg/lib/libx11.git"
commit="6c75545a1deb51f5903992c52af6bc35cc9bc103"
imagedeps="build-essential"
hostrundeps="automake autoconf libtool xorg-macros pkg-config xtrans"
hostdeps="gcc pkg-config xtrans"
deps="core-libs xorg-proto libXau libXdmcp libxtrans libxcb"

prepare() {
    NOCONFIGURE=1 ./autogen.sh
}

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
