#! /bin/sh

name=libXext
version=1.3.7
revision=1
git_url="https://gitlab.freedesktop.org/xorg/lib/libxext.git"
commit="2a694ba264ccdb205909909abfe8b136f9156ebe"
imagedeps="build-essential"
hostrundeps="automake autoconf libtool xorg-macros pkg-config xtrans"
hostdeps="gcc pkg-config xtrans"
deps="core-libs xorg-proto libX11 libxtrans xorg-util-macros"

prepare() {
    NOCONFIGURE=1 ./autogen.sh
}

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
