#! /bin/sh

name=libXt
version=1.3.7
revision=1
git_url="https://gitlab.freedesktop.org/xorg/lib/libXt.git"
commit="1dfcfa8dcc3958749849438a802d66728ccf3115"
imagedeps="build-essential"
hostrundeps="automake autoconf libtool xorg-macros pkg-config xtrans"
hostdeps="gcc pkg-config xtrans"
deps="core-libs xorg-proto libice libsm libX11 libxtrans xorg-util-macros"

prepare() {
    NOCONFIGURE=1 ./autogen.sh
}

configure() {
    autotools_configure \
        --disable-malloc0returnsnull \
        --with-appdefaultdir=/etc/X11/app-defaults
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
