#! /bin/sh

name=libxshmfence
version=1.3.3
revision=1
git_url="https://gitlab.freedesktop.org/xorg/lib/libxshmfence.git"
commit="89f064748554e11832a3ec783945e1f4c7fe846e"
imagedeps="build-essential"
hostrundeps="automake autoconf libtool xorg-macros pkg-config"
hostdeps="gcc pkg-config"
deps="core-libs xorg-util-macros xorg-proto libX11 libxtrans"

prepare() {
    NOCONFIGURE=1 ./autogen.sh
}

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
