#! /bin/sh

name=svr4_utils
version=1.0
revision=1
source_dir="extras/svr4_utils"
imagedeps="build-essential meson ninja-build"
hostdeps="gcc"
deps="core-libs"

configure() {
    meson_configure_noflags
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
