#! /bin/sh

name=svr4_iputils
version=1.0
revision=1
source_dir="extras/iputils"
imagedeps="build-essential meson ninja-build"
hostdeps="gcc"
deps="mlibc"

configure() {
    meson_configure_noflags
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild
    ln -svf svr4-ping "${dest_dir}${prefix}/bin/ping"

    post_package_strip
}
