#!/bin/bash

name=svr4_init
version=1.0
source_dir=extras/init
revision=1
imagedeps="build-essential meson ninja-build"
hostdeps="gcc"
deps="mlibc"

configure() {
    meson_configure_noflags
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}