#! /bin/sh

name=wsdemo
version=1.0
revision=1
source_dir="extras/wsdemo"
imagedeps="build-essential meson ninja-build"
hostdeps="gcc"
deps="mlibc"

configure() {
    meson_configure_noflags
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}