#! /bin/sh

name=xf86-video-svr4ws
version=0.1
revision=7
source_dir="extras/xf86-video-svr4ws"
imagedeps="build-essential meson ninja-build"
hostdeps="gcc pkg-config"
deps="core-libs xorg-server xorg-proto"

configure() {
    meson_configure_noflags
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}