#! /bin/sh

name=xinit
version=1.4.4
revision=1
git_url="https://gitlab.freedesktop.org/xorg/app/xinit.git"
commit="cfa71d44248562f22f2d92732c5e493e89061569"
imagedeps="build-essential"
hostrundeps="autoconf automake libtool xorg-macros pkg-config xtrans"
hostdeps="gcc autoconf automake libtool xorg-macros xtrans"
deps="core-libs svr4_utils xorg-proto libX11 xauth"

prepare() {
    NOCONFIGURE=1 ./autogen.sh
}

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
