#! /bin/sh

name=xorg-xeyes
repology_id=xeyes
version=1.3.1
revision=1
tarball_url="https://xorg.freedesktop.org/archive/individual/app/xeyes-${version}.tar.gz"
tarball_blake2b="143bec32c6e928f012ad7898d3948e70f59a1c4a6addb6ee828211b61e4ac66f8952addc6fdcdcd2fda6ea8c174c6c46cb970555490d4236a05ba77c1245a2ba"
hostdeps="gcc pkg-config"
deps="core-libs libX11 libXi libXt libXext libXmu libXrender xorg-proto"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure \
        --with-appdefaultdir=/etc/X11/app-defaults \
        --without-present
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
