#! /bin/sh

name=xorg-proto
version=2025.1
revision=1
tarball_url="https://xorg.freedesktop.org/archive/individual/proto/xorgproto-${version}.tar.xz"
tarball_blake2b="4202efbfe560afccb5a742f3c64973a4936878ed7ec4259bc31b7317e5cde505666fee2855dd0b6ff169a8da87d0f980dfa65ff58d2ead0aad39f3a94e053903"
hostdeps="gcc pkg-config"
deps="core-libs"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
