#! /bin/sh

name=xorg-macros
from_source=xorg-util-macros
revision=1
hostrundeps="automake autoconf libtool xorg-macros pkg-config"
hostdeps="gcc pkg-config"
deps="core-libs"

configure() {
        CFLAGS="$HOST_CFLAGS" \
        CXXFLAGS="$HOST_CXXFLAGS" \
        LDFLAGS="$HOST_LDFLAGS" \
    "${source_dir}"/configure --prefix="${prefix}"
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

        strip_command=strip \
    post_package_strip
}
