#! /bin/sh

name=cmake
from_source=cmake
revision=1
imagedeps="build-essential cmake libssl-dev"

configure() {
    "${source_dir}"/bootstrap \
        --prefix="${prefix}" \
        --parallel=${parallelism}
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR=${dest_dir} make install
    # Usually, you can use ${version} here, but CMake calls the current release 4.0.0
    cp -v ${base_dir}/support/svr4.cmake ${dest_dir}${prefix}/share/cmake-4.0/Modules/Platform/svr4.cmake
}
